import type { Metadata } from "next";
import { Poppins, Sriracha } from "next/font/google";
import Nav from "../components/nav";
import "./globals.css";
import { SrirachaProvider } from "@/context/srirachaContext";

const sriracha = Sriracha({
  weight: "400",
  subsets: ["latin"],
});
export const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SrirachaProvider>
        <body className={sriracha.className}>
          <Nav />
          {children}
        </body>
      </SrirachaProvider>
    </html>
  );
}
