import type { Metadata } from "next";
import { Poppins, Sriracha } from "next/font/google";
import "./globals.css";

const sriracha = Sriracha({
  weight: "400",
  subsets: ["latin"],
});
export const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sriracha.className}>
        insert nav component here
        <nav></nav>
        {children}</body>
    </html>
  );
}
